Allow CF_API and CF_API_SECURE to be empty
CF_API_SECURE did not have a default and broke in CI.

Also, this is useful when testing bosh releases in Dev so you don't have to
set CF_API or CF_API_SECURE.

A test is added before connecting to cf api as if the variable is empty,
the command hangs without telling the user why.

diff --git a/pipelines/deploy-app.yml b/pipelines/deploy-app.yml
--- a/pipelines/deploy-app.yml
+++ b/pipelines/deploy-app.yml
@@ -89,8 +89,11 @@ jobs:
               - -e
               - -u
               - -c
-              - -x
               - |
+                if [ -z "${CF_API}" ]; then
+                  echo "\$CF_API is empty, cannot connect to CF API"
+                  exit 1
+                fi
                 echo Logging on to Cloudfoundry...
                 cf login "${CF_API_SECURE:-}" -a "${CF_API}" -u "${CF_USER}" \
                 -p "${CF_PASSWORD}" -o "${CF_ORG}" -s "${CF_SPACE}"
